/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ben
 */
public class PirateTranslator extends javax.swing.JFrame {

    /**
     * Creates new form PirateTranslator
     */
    public PirateTranslator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdjectives = new javax.swing.JLabel();
        lblVerbs = new javax.swing.JLabel();
        lblNouns = new javax.swing.JLabel();
        lblArticles = new javax.swing.JLabel();
        lblGreetings = new javax.swing.JLabel();
        btnHappy = new javax.swing.JButton();
        btnOld = new javax.swing.JButton();
        btnAttractive = new javax.swing.JButton();
        btnCool = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnIDesire = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnTake = new javax.swing.JButton();
        btnMe = new javax.swing.JButton();
        btnRestraunt = new javax.swing.JButton();
        btnTreasure = new javax.swing.JButton();
        btnPub = new javax.swing.JButton();
        btnTo = new javax.swing.JButton();
        btnThe = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        bynNearby = new javax.swing.JButton();
        lblPunctuation = new javax.swing.JLabel();
        btnHello = new javax.swing.JButton();
        btnPardonMe = new javax.swing.JButton();
        btnExcuseMe = new javax.swing.JButton();
        btnSir = new javax.swing.JButton();
        btnPeriod = new javax.swing.JButton();
        btnQuestionMark = new javax.swing.JButton();
        btnComma = new javax.swing.JButton();
        btnExplanationPoint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAdjectives.setText("Adjectives");

        lblVerbs.setText("Verbs");

        lblNouns.setText("Nouns");

        lblArticles.setText("Articles");

        lblGreetings.setText("Greetings");

        btnHappy.setBackground(new java.awt.Color(255, 0, 0));
        btnHappy.setText("Happy");
        btnHappy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHappyMouseClicked(evt);
            }
        });

        btnOld.setBackground(new java.awt.Color(255, 0, 0));
        btnOld.setText("Old");
        btnOld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOldMouseClicked(evt);
            }
        });

        btnAttractive.setBackground(new java.awt.Color(255, 0, 0));
        btnAttractive.setText("Attractive");
        btnAttractive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAttractiveMouseClicked(evt);
            }
        });

        btnCool.setBackground(new java.awt.Color(255, 0, 0));
        btnCool.setText("Cool");
        btnCool.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCoolMouseClicked(evt);
            }
        });

        btnFind.setBackground(new java.awt.Color(255, 102, 0));
        btnFind.setText("Find");
        btnFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFindMouseClicked(evt);
            }
        });

        btnIDesire.setBackground(new java.awt.Color(255, 102, 0));
        btnIDesire.setText("I Desire");
        btnIDesire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIDesireMouseClicked(evt);
            }
        });
        btnIDesire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDesireActionPerformed(evt);
            }
        });

        btnHelp.setBackground(new java.awt.Color(255, 102, 0));
        btnHelp.setText("Help");
        btnHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHelpMouseClicked(evt);
            }
        });
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        btnTake.setBackground(new java.awt.Color(255, 102, 0));
        btnTake.setText("Take");
        btnTake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTakeMouseClicked(evt);
            }
        });

        btnMe.setBackground(new java.awt.Color(0, 0, 204));
        btnMe.setText("Me");
        btnMe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMeMouseClicked(evt);
            }
        });

        btnRestraunt.setBackground(new java.awt.Color(0, 0, 204));
        btnRestraunt.setText("Restraunt");
        btnRestraunt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRestrauntMouseClicked(evt);
            }
        });

        btnTreasure.setBackground(new java.awt.Color(0, 0, 204));
        btnTreasure.setText("Treasure");
        btnTreasure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTreasureMouseClicked(evt);
            }
        });

        btnPub.setBackground(new java.awt.Color(0, 0, 204));
        btnPub.setText("Pub");
        btnPub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPubMouseClicked(evt);
            }
        });

        btnTo.setBackground(new java.awt.Color(0, 102, 0));
        btnTo.setText("To");
        btnTo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnToMouseClicked(evt);
            }
        });

        btnThe.setBackground(new java.awt.Color(0, 102, 0));
        btnThe.setText("The");
        btnThe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTheMouseClicked(evt);
            }
        });
        btnThe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTheActionPerformed(evt);
            }
        });

        btnA.setBackground(new java.awt.Color(0, 102, 0));
        btnA.setText("A");
        btnA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAMouseClicked(evt);
            }
        });

        bynNearby.setBackground(new java.awt.Color(0, 102, 0));
        bynNearby.setText("Nearby");
        bynNearby.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bynNearbyMouseClicked(evt);
            }
        });
        bynNearby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bynNearbyActionPerformed(evt);
            }
        });

        lblPunctuation.setText("Punctuation");

        btnHello.setBackground(new java.awt.Color(153, 0, 153));
        btnHello.setText("Hello");
        btnHello.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHelloMouseClicked(evt);
            }
        });
        btnHello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelloActionPerformed(evt);
            }
        });

        btnPardonMe.setBackground(new java.awt.Color(153, 0, 153));
        btnPardonMe.setText("Pardon Me");
        btnPardonMe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPardonMeMouseClicked(evt);
            }
        });

        btnExcuseMe.setBackground(new java.awt.Color(153, 0, 153));
        btnExcuseMe.setText("Excuse Me");
        btnExcuseMe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcuseMeMouseClicked(evt);
            }
        });

        btnSir.setBackground(new java.awt.Color(153, 0, 153));
        btnSir.setText("Sir");
        btnSir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSirMouseClicked(evt);
            }
        });

        btnPeriod.setText(".");
        btnPeriod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPeriodMouseClicked(evt);
            }
        });
        btnPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeriodActionPerformed(evt);
            }
        });

        btnQuestionMark.setText("?");
        btnQuestionMark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuestionMarkMouseClicked(evt);
            }
        });

        btnComma.setText(",");
        btnComma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCommaMouseClicked(evt);
            }
        });
        btnComma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommaActionPerformed(evt);
            }
        });

        btnExplanationPoint.setText("!");
        btnExplanationPoint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExplanationPointMouseClicked(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdjectives)
                            .addComponent(lblVerbs)
                            .addComponent(lblNouns)
                            .addComponent(lblArticles))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnThe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bynNearby))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRestraunt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTreasure)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPub))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFind)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIDesire)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHelp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTake))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnHappy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOld)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAttractive)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCool))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGreetings)
                            .addComponent(lblPunctuation))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPeriod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnQuestionMark)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnComma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExplanationPoint))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnHello)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPardonMe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcuseMe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSir)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClear)
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAdjectives)
                            .addComponent(btnHappy)
                            .addComponent(btnOld)
                            .addComponent(btnAttractive)
                            .addComponent(btnCool))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVerbs)
                            .addComponent(btnFind)
                            .addComponent(btnIDesire)
                            .addComponent(btnHelp)
                            .addComponent(btnTake))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNouns)
                            .addComponent(btnMe)
                            .addComponent(btnRestraunt)
                            .addComponent(btnTreasure)
                            .addComponent(btnPub))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblArticles)
                            .addComponent(btnTo)
                            .addComponent(btnThe)
                            .addComponent(btnA)
                            .addComponent(bynNearby))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGreetings, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPardonMe)
                            .addComponent(btnExcuseMe)
                            .addComponent(btnSir)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPunctuation)
                    .addComponent(btnPeriod)
                    .addComponent(btnQuestionMark)
                    .addComponent(btnComma)
                    .addComponent(btnExplanationPoint))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIDesireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDesireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIDesireActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHelpActionPerformed

    private void bynNearbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bynNearbyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bynNearbyActionPerformed

    private void btnHelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHelloActionPerformed

    private void btnPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeriodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeriodActionPerformed

    private void btnCommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCommaActionPerformed

    private void btnHappyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHappyMouseClicked
        jTextArea1.append("grog-filled ");
    }//GEN-LAST:event_btnHappyMouseClicked

    private void btnOldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOldMouseClicked
        jTextArea1.append("barnacle-covered ");
    }//GEN-LAST:event_btnOldMouseClicked

    private void btnAttractiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAttractiveMouseClicked
        jTextArea1.append("comely ");
    }//GEN-LAST:event_btnAttractiveMouseClicked

    private void btnCoolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCoolMouseClicked
        jTextArea1.append("Arrrgly Awsome ");
    }//GEN-LAST:event_btnCoolMouseClicked

    private void btnTheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTheActionPerformed

    private void btnFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindMouseClicked
        jTextArea1.append("come accross ");
    }//GEN-LAST:event_btnFindMouseClicked

    private void btnIDesireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIDesireMouseClicked
        jTextArea1.append("I've a fierce fire in me belly t' ");
    }//GEN-LAST:event_btnIDesireMouseClicked

    private void btnHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMouseClicked
        jTextArea1.append("'elp ");
    }//GEN-LAST:event_btnHelpMouseClicked

    private void btnTakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTakeMouseClicked
        jTextArea1.append("have a bit of ");
    }//GEN-LAST:event_btnTakeMouseClicked

    private void btnMeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMeMouseClicked
        jTextArea1.append("ye ");
    }//GEN-LAST:event_btnMeMouseClicked

    private void btnRestrauntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestrauntMouseClicked
        jTextArea1.append("galley ");
    }//GEN-LAST:event_btnRestrauntMouseClicked

    private void btnTreasureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTreasureMouseClicked
        jTextArea1.append("booty ");
    }//GEN-LAST:event_btnTreasureMouseClicked

    private void btnPubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPubMouseClicked
        jTextArea1.append("Skull & Scuppers ");
    }//GEN-LAST:event_btnPubMouseClicked

    private void btnToMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnToMouseClicked
        jTextArea1.append("t' ");
    }//GEN-LAST:event_btnToMouseClicked

    private void btnTheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTheMouseClicked
        jTextArea1.append("th' ");
    }//GEN-LAST:event_btnTheMouseClicked

    private void btnAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAMouseClicked
        jTextArea1.append("a briny ");
    }//GEN-LAST:event_btnAMouseClicked

    private void bynNearbyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bynNearbyMouseClicked
        jTextArea1.append("broadside ");
    }//GEN-LAST:event_bynNearbyMouseClicked

    private void btnHelloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelloMouseClicked
        jTextArea1.append("ahoy ");
    }//GEN-LAST:event_btnHelloMouseClicked

    private void btnPardonMeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPardonMeMouseClicked
        jTextArea1.append("avast matey ");
    }//GEN-LAST:event_btnPardonMeMouseClicked

    private void btnExcuseMeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcuseMeMouseClicked
        jTextArea1.append("arrrrrr ");
    }//GEN-LAST:event_btnExcuseMeMouseClicked

    private void btnSirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSirMouseClicked
        jTextArea1.append("matey ");
    }//GEN-LAST:event_btnSirMouseClicked

    private void btnPeriodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeriodMouseClicked
        jTextArea1.append(". ");
    }//GEN-LAST:event_btnPeriodMouseClicked

    private void btnQuestionMarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuestionMarkMouseClicked
        jTextArea1.append("? ");
    }//GEN-LAST:event_btnQuestionMarkMouseClicked

    private void btnCommaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCommaMouseClicked
        jTextArea1.append(", ");
    }//GEN-LAST:event_btnCommaMouseClicked

    private void btnExplanationPointMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExplanationPointMouseClicked
        jTextArea1.append("! ");
    }//GEN-LAST:event_btnExplanationPointMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        jTextArea1.setText("");
    }//GEN-LAST:event_btnClearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PirateTranslator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PirateTranslator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PirateTranslator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PirateTranslator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PirateTranslator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnAttractive;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnComma;
    private javax.swing.JButton btnCool;
    private javax.swing.JButton btnExcuseMe;
    private javax.swing.JButton btnExplanationPoint;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnHappy;
    private javax.swing.JButton btnHello;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnIDesire;
    private javax.swing.JButton btnMe;
    private javax.swing.JButton btnOld;
    private javax.swing.JButton btnPardonMe;
    private javax.swing.JButton btnPeriod;
    private javax.swing.JButton btnPub;
    private javax.swing.JButton btnQuestionMark;
    private javax.swing.JButton btnRestraunt;
    private javax.swing.JButton btnSir;
    private javax.swing.JButton btnTake;
    private javax.swing.JButton btnThe;
    private javax.swing.JButton btnTo;
    private javax.swing.JButton btnTreasure;
    private javax.swing.JButton bynNearby;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAdjectives;
    private javax.swing.JLabel lblArticles;
    private javax.swing.JLabel lblGreetings;
    private javax.swing.JLabel lblNouns;
    private javax.swing.JLabel lblPunctuation;
    private javax.swing.JLabel lblVerbs;
    // End of variables declaration//GEN-END:variables
}
