/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Feb 26, 2013, 12:45:38 PM
 */

import javax.swing.*;


/**
 *
 * @author 151146
 */
public class NewJFrame extends javax.swing.JFrame {

    private int questionNumber = 0;
    private boolean dog = false;
    private boolean reptiles = false;
    private boolean lizards = false;
    private boolean fish = false;
    private boolean mammals = false;
    
    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnYes = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblanimalHelper = new javax.swing.JLabel();
        lblQuestions = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaResponse = new javax.swing.JTextArea();
        lblpicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnYes.setBackground(new java.awt.Color(0, 153, 0));
        btnYes.setText("Yes");
        btnYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnYesMouseClicked(evt);
            }
        });

        btnNo.setBackground(new java.awt.Color(0, 0, 204));
        btnNo.setText("No");
        btnNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNoMouseClicked(evt);
            }
        });

        btnStart.setBackground(new java.awt.Color(255, 204, 0));
        btnStart.setText("Start");
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMouseClicked(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        lblanimalHelper.setBackground(new java.awt.Color(0, 153, 153));
        lblanimalHelper.setFont(new java.awt.Font("Tahoma", 0, 24));
        lblanimalHelper.setText("Animal Helper");
        lblanimalHelper.setMaximumSize(new java.awt.Dimension(75, 24));
        lblanimalHelper.setMinimumSize(new java.awt.Dimension(75, 24));
        lblanimalHelper.setPreferredSize(new java.awt.Dimension(75, 24));

        txtaResponse.setColumns(20);
        txtaResponse.setRows(5);
        jScrollPane1.setViewportView(txtaResponse);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblpicture, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnYes)
                                .addGap(18, 18, 18)
                                .addComponent(btnNo)
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblanimalHelper, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(lblQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStart)
                    .addComponent(btnExit))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblanimalHelper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnStart)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblQuestions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYes)
                    .addComponent(btnNo))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(lblpicture, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked
        //set-up
        lblQuestions.setEnabled(true);
        btnYes.setEnabled(true);
        btnNo.setEnabled(true);
        
        //questioning
        lblQuestions.setText("Do you like dogs?");
        txtaResponse.setText("");
        lblpicture.setIcon(null);
        questionNumber = 0;
        dog = false;
        reptiles = false;
        lizards = false;
        fish = false;
        mammals = false;
}//GEN-LAST:event_btnStartMouseClicked

private void btnNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoMouseClicked

    questionNumber++;
    processResponse();

}//GEN-LAST:event_btnNoMouseClicked

private void btnYesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYesMouseClicked

    switch (questionNumber)
    {
        case 0:
            dog = true;
            questionNumber++;
            break;
        case 1:
            reptiles = true;
            questionNumber++;
            break;
        case 2:
            lizards = true;
            fish = true;
            questionNumber++;
            break;
        case 3:
            mammals = true;
            questionNumber++;
            lblQuestions.setEnabled(false);
            btnYes.setEnabled(false);
            btnNo.setEnabled(false);
            break;
        default:
            break;
    }
    
    processResponse();
}//GEN-LAST:event_btnYesMouseClicked

private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
       
    System.exit(0);
}//GEN-LAST:event_btnExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {       
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    private void processResponse()
    {
        // Clear out the response text area.
        txtaResponse.setText("");
        
        
        // Check for a valid question number range.
        
        if (questionNumber >= 1 && questionNumber <= 4)
        {
            processDogQuestion();
        }
        else // Invalid Question Number
        {
            txtaResponse.append("Application Error: Please contact the developer!\n");
        }
    }
            
    private void processDogQuestion()
    {
            // Do they like dogs?
        if (questionNumber >= 1)
        {
            if (dog == true) // Yes, they do.
            {
                   lblpicture.setIcon((Icon) (new ImageIcon(this.getClass().getResource("/images/dscf5037_thumb.jpg"))));
                   txtaResponse.append("You got fuzzed!\n");
            
                   lblQuestions.setText("Are reptiles cool?");
                   
                   processReptilesQuestion();
            }
            else // Well, they must be a cat instead.
            {
                   lblpicture.setIcon((Icon) (new ImageIcon(this.getClass().getResource("/images/dsc_0010_thumb.jpg"))));
                   txtaResponse.append("You are a Cat! Meow!\n");
                   
                               lblQuestions.setEnabled(false);
                               btnYes.setEnabled(false);
                               btnNo.setEnabled(false);
            }
       }
    }
                   
    private void processReptilesQuestion()
    {
        if (questionNumber >= 2)
        {
            if (reptiles == true)
            {
                   lblpicture.setIcon((Icon) (new ImageIcon(this.getClass().getResource("/images/alligator6_thumb.jpg"))));
                   txtaResponse.append("You must be a gator's fan!\n");
            
                   lblQuestions.setText("Do you like lizards?"); 
                   
                   processLizardQuestion();
            }
            else
            {
                
            }
                 if (reptiles == false)
                 {
                   lblpicture.setIcon((Icon) (new ImageIcon(this.getClass().getResource("/images/alligator6_thumb.jpg"))));
                   txtaResponse.append("Scared of those scaley things? That's alright.\n");
            
                   lblQuestions.setText("Are fish interesting to you?"); 
                   
                   processFishQuestion();
                 }
                 else
                 {
                     
                 }
        }
        else
        {
            
        }
    }
    
    private void processLizardQuestion()
    {
        if (questionNumber >= 3)
        {
            if (lizards == true)
            {
                   lblpicture.setIcon((Icon) (new ImageIcon(this.getClass().getResource("/images/redheadlizard2_thumb.jpg"))));
                   txtaResponse.append("You are a lizard! Hope you like the desert.\n");       
                                      lblQuestions.setEnabled(false);
                                      btnYes.setEnabled(false);
                                      btnNo.setEnabled(false);
            }
            else
            {
                
            }
                 if (lizards == false)
                 {
                   lblpicture.setIcon((Icon) (new ImageIcon(this.getClass().getResource("/images/frog31_thumb.jpg"))));
                   txtaResponse.append("You are a frog! Better find a nice pond!\n");
                             lblQuestions.setEnabled(false);
                             btnYes.setEnabled(false);
                             btnNo.setEnabled(false);
                 }
                 else
                 {
                     
                 }
        }
        else
        {
            
        }
    }
    
    private void processFishQuestion()
    {
        if (questionNumber >= 3)
        {
            if (fish == true)
            {
                   lblpicture.setIcon((Icon) (new ImageIcon(this.getClass().getResource("/images/tigerfish21_thumb.jpg"))));
                   txtaResponse.append("'Just keep swimming!'\n");
            
                   lblQuestions.setText("Do you like horses?");   
            
                   processMammalsQuestion();
            }
            else
            {
            
            }
                if (fish == false)
                {
                   lblpicture.setIcon((Icon) (new ImageIcon(this.getClass().getResource("/images/hummerforpics_thumb.jpg"))));
                   txtaResponse.append("Allergic to water? You must be a bird!\n"); 
                            lblQuestions.setEnabled(false);
                            btnYes.setEnabled(false);
                            btnNo.setEnabled(false);
                }
                else
                {
                           
                }
        }
    
        else
        {
        
        }
    }  
    
    private void processMammalsQuestion()
    {
        if (questionNumber >= 4)
        {
            if (mammals == true)
            {
                   lblpicture.setIcon((Icon) (new ImageIcon(this.getClass().getResource("/images/clydesdale_thumb.jpg"))));
                   txtaResponse.append("You are a horse! Hope you know how to ride one.\n");
                        lblQuestions.setEnabled(false);
                        btnYes.setEnabled(false);
                        btnNo.setEnabled(false);
            }
            else
            {
                    lblpicture.setIcon((Icon) (new ImageIcon(this.getClass().getResource("/images/img_01751_thumb.jpg"))));
                    txtaResponse.append("'I will call him squishy and he will be mine!' You are a Fish!\n");
                        lblQuestions.setEnabled(false);
                        btnYes.setEnabled(false);
                        btnNo.setEnabled(false);
            }
        }
        else
        {
        
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnYes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQuestions;
    private javax.swing.JLabel lblanimalHelper;
    private javax.swing.JLabel lblpicture;
    private javax.swing.JTextArea txtaResponse;
    // End of variables declaration//GEN-END:variables
}
