/*
 * bbHelper.java
 *
 * Created on October 5, 2012, 12:10 PM
 */

import javax.swing.*;


/**
 *  
 * @author  hoffertm
 */
public class bbHelper extends javax.swing.JFrame {
    
    private int questionNumber = 0;
    private boolean baseball = false;
    private boolean nationalLeague = false;
    private boolean redUniforms = false;
    private boolean ohio = false;

    /** Creates new form bbHelper */
    public bbHelper() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTeamPic = new javax.swing.JLabel();
        btnYes = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        pnlResponse = new javax.swing.JScrollPane();
        txtaResponse = new javax.swing.JTextArea();
        lblQuestion = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnYes.setText("Yes");
        btnYes.setEnabled(false);
        btnYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnYesMouseClicked(evt);
            }
        });

        btnNo.setText("No");
        btnNo.setEnabled(false);
        btnNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNoMouseClicked(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("BankGothic Md BT", 0, 24));
        lblTitle.setForeground(new java.awt.Color(0, 0, 204));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Baseball Helper");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtaResponse.setColumns(20);
        txtaResponse.setFont(new java.awt.Font("Cambria", 0, 18));
        txtaResponse.setLineWrap(true);
        txtaResponse.setRows(5);
        txtaResponse.setWrapStyleWord(true);
        pnlResponse.setViewportView(txtaResponse);

        lblQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuestion.setEnabled(false);

        btnStart.setText("Start");
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMouseClicked(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblTeamPic, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(btnYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(btnNo)
                                .addGap(48, 48, 48))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit))
                    .addComponent(pnlResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTeamPic, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnYes)
                            .addComponent(btnNo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked

    // Enable controls associated with your line of questioning.
    lblQuestion.setEnabled(true);
    btnYes.setEnabled(true);
    btnNo.setEnabled(true);
    
   // Now begin the line of questioning...
    lblQuestion.setText("Do you like America's pastime?");
    txtaResponse.setText("");
    lblTeamPic.setIcon(null);
    questionNumber = 0;
    baseball = false;
    nationalLeague = false;
    redUniforms = false;
    ohio = false;
}//GEN-LAST:event_btnStartMouseClicked

private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked

    System.exit(0);
}//GEN-LAST:event_btnExitMouseClicked

private void btnYesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYesMouseClicked

    switch (questionNumber)
    {
        case 0:
            baseball = true;
            questionNumber++;
            break;
        case 1:
            nationalLeague = true;
            questionNumber++;
            break;
        case 2:
            redUniforms = true;
            questionNumber++;
            break;
        case 3:
            ohio = true;
            questionNumber++;
            lblQuestion.setEnabled(false);
            btnYes.setEnabled(false);
            btnNo.setEnabled(false);
            break;
        default:
            break;
    }
    
    processResponse();
}//GEN-LAST:event_btnYesMouseClicked

private void btnNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoMouseClicked

    questionNumber++;
    processResponse();
    
    // For my flowchart, a 'no' response is the end.
    lblQuestion.setEnabled(false);
    btnYes.setEnabled(false);
    btnNo.setEnabled(false);
}//GEN-LAST:event_btnNoMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bbHelper().setVisible(true);
            }
        });
    }

    private void processResponse()
    {
        // Clear out the response text area.
        txtaResponse.setText("");
        
        
        // Check for a valid question number range.
        
        if (questionNumber >= 1 && questionNumber <= 4)
        {
            processBaseballQuestion();
        }
        else // Invalid Question Number
        {
            txtaResponse.append("Application Error: Please contact the developer!\n");
        }
    }
    
    private void processBaseballQuestion()
    {
        // Does the user like baseball?
            
        if (questionNumber >= 1)
        {
            if (baseball) // Yes, they do.
            {
               lblTeamPic.setIcon((Icon) (new ImageIcon(this.getClass().getResource("/images/mlb2Fit.gif"))));
               txtaResponse.append("Play Ball!\n");

               processLeagueQuestion();
            }
            else // Well, maybe they like cricket.
            {
               lblTeamPic.setIcon((Icon) (new ImageIcon(this.getClass().getResource("/images/cricketFit.gif"))));
               txtaResponse.append("Been to India lately?\n");
            }
        }
    }
    
    private void processLeagueQuestion()
    {
        lblQuestion.setText("Do you prefer the National League?");

       if (questionNumber >= 2)
       {
           if (nationalLeague)
           {
               lblTeamPic.setIcon((Icon) (new ImageIcon(this.getClass().getResource("/images/NLFit.gif"))));
               txtaResponse.append("Welcome to the Majors!\n");

               processRedUniformsQuestion();
           }
           else
           {
               lblTeamPic.setIcon((Icon) (new ImageIcon(this.getClass().getResource("/images/oriolesFit.gif"))));
               txtaResponse.append("Must be an Orioles fan.\n");
           }
       }
    }
    private void processRedUniformsQuestion()
    {
                lblQuestion.setText("Do you like red uniforms?");

       if (questionNumber >= 3)
       {
           if (redUniforms)
           {
               lblTeamPic.setIcon((Icon) (new ImageIcon(this.getClass().getResource("/images/nlcFit.gif"))));
               txtaResponse.append("The Central Division is the best!\n");

               processOhioQuestion();
           }
           else
           {
               lblTeamPic.setIcon((Icon) (new ImageIcon(this.getClass().getResource("/images/dodgersFit.gif"))));
               txtaResponse.append("Good luck with the Dodgers.\n");
           }
       }
    }
    private void processOhioQuestion()
    {
                lblQuestion.setText("Are you also a Buckeye fan?");

       if (questionNumber >= 4)
       {
           if (ohio)
           {
               lblTeamPic.setIcon((Icon) (new ImageIcon(this.getClass().getResource("/images/redsFit.gif"))));
               txtaResponse.append("Go Reds!\n");
           }
           else
           {
               lblTeamPic.setIcon((Icon) (new ImageIcon(this.getClass().getResource("/images/cardinalsFit.gif"))));
               txtaResponse.append("Go Cards!\n");
           }
       }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnYes;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblTeamPic;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane pnlResponse;
    private javax.swing.JTextArea txtaResponse;
    // End of variables declaration//GEN-END:variables

}
